# CodeRabbit Configuration
# This file configures CodeRabbit AI code review behavior

# Language settings
language:
  # Enable reviews for these languages
  - typescript
  - javascript
  - json
  - yaml
  - markdown

# Review settings
review:
  # Request review comments on pull requests
  request_changes_workflow: true
  
  # Review only changed lines or entire file
  review_only_changed_files: false
  
  # Paths to ignore
  ignore:
    - "**/*.lock"
    - "**/node_modules/**"
    - "**/dist/**"
    - "**/.git/**"
    - "**/coverage/**"
    - "**/*.min.js"
    - "**/*.bundle.js"

# Suggestions settings
suggestions:
  # Enable code suggestions
  enabled: true
  
  # Language-specific settings
  typescript:
    # Suggest improvements for TypeScript code
    enabled: true
  
  javascript:
    # Suggest improvements for JavaScript code
    enabled: true

# Chat settings (for Pro plan)
chat:
  # Enable chat with CodeRabbit
  enabled: true

# Summarization settings
summarization:
  # Enable PR summarization
  enabled: true
  
  # Include diff summary
  diff_summary: true

